application: instagram-atom
version: 3
runtime: python27
threadsafe: true
api_version: 1
default_expiration: 1d

builtins:
- remote_api: on

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /oauth_dropins/static
  static_dir: local/lib/python2.7/site-packages/oauth_dropins/static

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /atom
  script: main.application
  secure: always

- url: /cookie
  script: cookie.application
  secure: always

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|docs?|examples?|l|pydocs?|python3|ref|samples?|tests?)/.*
